#!/bin/bash


version=`hg summary | grep parent | sed 's/.*:[^0-9]\([0-9][0-9]*\).*/\1/g'`

tar --exclude=debug --exclude=release --exclude=profile --exclude=.hg \
    --exclude=distribute \
    -C ../ \
    -vz \
    -cf distribute/graphlab_v${version}.tar.gz \
    graphlabapi



