#!/bin/bash


mkdir dist/graphlabapi
rsync --verbose --recursive --links --times --owner --perms --delete \
    --exclude=debug --exclude=release --exclude=profile --exclude=apps --exclude=.hg \
    --exclude=dist \
    * dist/graphlabapi/.

mkdir dist/graphlabapi/apps
cp dist/graphlabapi/demoapps/CMakeLists.txt dist/graphlabapi/apps/
version=`hg summary | grep parent | sed 's/parent: //g' | sed 's/:.*//g'`
echo "Version: $version"


cd dist
tar -vz \
    -cf graphlabapi_v${version}.tar.gz \
    graphlabapi
    



