#PBS -N run_pagerank
#PBS -l nodes=7:ppn=8 -k oe

echo $PBS_NODEFILE && cat $PBS_NODEFILE | uniq > .mfile
CLASSPATH=$CLASSPATH:`hadoop classpath`

/opt/openmpi/bin/mpiexec -machinefile .mfile -np 14 \
        -x CLASSPATH \
        ./distributed_pagerank --graph hdfs://bros.ml.cmu.edu/users/jegonzal/webgraphs/domain_graph/edata_splits/ \
        --ncpus=8 \
        --dgraphopts="(ingress=random)"

rm .mfile
exit 0