#PBS -N pagerank
#PBS -l nodes=7:ppn=8 -k oe -d

cat $PBS_NODEFILE | uniq > .mfile
CLASSPATH=$CLASSPATH:`hadoop classpath`

/opt/openmpi/bin/mpiexec \
        --hostfile .mfile -n 14 \
        -x CLASSPATH \
        ./dist_fscope_pagerank \
        --graph hdfs://bros.ml.cmu.edu/data/webgraphs/domain_graph/edata_random_snap/ \
        --format=snap \
        --ncpus=8 \
        --dgraphopts="(ingress=oblivious)"

rm .mfile
exit 0