

mex -largeArrayDims ...
   -I../../src ...
   -L../../release/src/graphlab/extern/metis/libmetis ...
   -L../../release/src/graphlab/extern/metis/GKlib ...
   -lgraphlab_metis_pic ...
   -lgraphlab_GKlib_pic ...
   metiscut.cpp


% mex -I/opt/metis-4.0/include ...
%    -L/opt/metis-4.0/lib ...
%    -lmetis ...
%    -largeArrayDims ...
%    metiscut.cpp
