#ifndef GRAPHLAB_VERSION_HPP
#define GRAPHLAB_VERSION_HPP

#define GRAPHLAB_VERSION "1_0_0"

#define GRAPHLAB_VERSION_MAJOR 1
#define GRAPHLAB_VERSION_MINOR 0
#define GRAPHLAB_VERSION_REVISION 0

#endif