/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_demo_ShortestPath */

#ifndef _Included_org_graphlab_demo_ShortestPath
#define _Included_org_graphlab_demo_ShortestPath
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
