/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Context */

#ifndef _Included_org_graphlab_Context
#define _Included_org_graphlab_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graphlab_Context
 * Method:    schedule
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_graphlab_Context_schedule
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
