/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Core_CoreException */

#ifndef _Included_org_graphlab_Core_CoreException
#define _Included_org_graphlab_Core_CoreException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_graphlab_Core_CoreException_serialVersionUID
#define org_graphlab_Core_CoreException_serialVersionUID -3042686055658047285LL
#undef org_graphlab_Core_CoreException_serialVersionUID
#define org_graphlab_Core_CoreException_serialVersionUID -3387516993124229948LL
#undef org_graphlab_Core_CoreException_serialVersionUID
#define org_graphlab_Core_CoreException_serialVersionUID -1231034883125084972LL
#ifdef __cplusplus
}
#endif
#endif
