/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Updater */

#ifndef _Included_org_graphlab_Updater
#define _Included_org_graphlab_Updater
#endif
